### ISSUE TITLE
Sample do not work

### ISSUE THREAD

**Issue by pvint** [vintlabs/fauxmoESP#114]
**[Original report](https://bitbucket.org/xoseperez/fauxmoesp/issue/114) by Edu C R (Bitbucket: [edurochaN](https://bitbucket.org/edurochaN), ).**

----------------------------------------

Hi everyone, I downloaded the source code, opened the file fauxmoESP.ino, has compiled successfully, but my Alexa APP do not found the device.

I'm using ESP32, board Node32s, FauxmoESP 3.1.1. Someone has the same problem?

**Comment by pvint** [comment]
A common problem is with an older version of th eAsyncTCP library - be sure that is up to date and test.

If you get the same issue, in your code please set:
`#define DEBUG_FAUXMO                Serial`
then post the output and your code.

**Comment by ddweber456** [comment]
Looks like several issues have been raised with the same problem.  Look at #120 ESP 8266 not found.
