### ISSUE TITLE
Grouping devices together and trying the On Off button on Alexa App crashes the ESP.

### ISSUE THREAD

**Issue by Tejas-MD** [vintlabs/fauxmoESP#118]
While I understand that operating through the switches in the Alexa app isn't implemented in this library, I think there should be handling it atleast. Like, if by mistake someone uses that, it is better if the command is ignored voluntarily than abruptly crashing the device... (If this is technically possible).

**Comment by pvint** [comment]
I do this all the time - for example on my boat I have 8 different fauxmo devices in a group... I have had the same problem, and the real cause was having too much going on in fauxmo.onSetState() - you want to be sure you exit that call as quickly as possible.

**Comment by pvint** [comment]
Also, see #115 - I think I made a change to do exactly what you want there! I have committed that change in the dev branch - would appreciate if you can give it a try.

**Comment by Tejas-MD** [comment]
> I do this all the time - for example on my boat I have 8 different fauxmo devices in a group... I have had the same problem, and the real cause was having too much going on in fauxmo.onSetState() - you want to be sure you exit that call as quickly as possible.

So this means if the buttons on the Alexa app crash the ESP, it's because of the `fauxmo.onSetState()` not returning quick? 
Have you tried to operate it with the on/off buttons after grouping devices in the Alexa app?

**Comment by pvint** [comment]
Sorry for not having responded to this earlier.

Correct, if onSetState takes too long you can get into trouble. I routinely use it with on/off in groups in the app.
