### ISSUE TITLE
Fauxmo library V3.1.1 fragmentation raises to 100% and ESP reboots with Exception 3.

### ISSUE THREAD

**Issue by jjsanma1** [vintlabs/fauxmoESP#119]
Hi , I’m using I’m using the Fauxmo library V3.1.1 with “fauxmoESP_Basic.ino” example in a NodeMCU (also same issue in a stand alone ESP8266-12F chip) . The problem is that fragmentation raises to 100% after some minuts and so , the ESP reboots with Exception 3.

**Comment by pvint** [comment]
This will be "on hold" until the discovery issue is settled - see #120

**Comment by pvint** [comment]
Can you still reproduce the issue?

**Comment by jjsanma1** [comment]
hello , I can't answer since I moved to this library https://github.com/kakopappa/arduino-esp8266-alexa-multiple-wemo-switch/tree/master/wemos and  it is working well.

**Comment by pvint** [comment]
Ok. I've been unable to reproduce the issue, so I'll close this. Feel free to reopen if you have the issue in the future.
