### ISSUE TITLE
Why haven't we thought of adding Google Home support?

### ISSUE THREAD

**Issue by Tejas-MD** [vintlabs/fauxmoESP#124]
I just read about Phillips Hue having a Google Home integration too and if I'm right, we should be able to integrate Google Home too, similar to Alexa.

**Comment by pvint** [comment]
I've been thinking the same thing. Once we get through some current issues with Amazon Echo I'll definitely look into this.  Might be fairly easy, might be near impossible....

**Comment by Tejas-MD** [comment]
This is one option, but the Javascript part might be a little hard: https://developers.google.com/assistant/smarthome/concepts/local

**Comment by pvint** [comment]
Just took a quick glance and my knee-jerk reaction is that even if that's not the path to use, it looks like it's a good way to understand the process. Thanks!

**Comment by pvint** [comment]
I did some playing around with this recently, and in order to add a Hue device on Google it needs to connect to your account with Philips (meethue I think it was?). Since it's using a third-party cloud based service, I think it's out of our hands and out of the scope of this project.
