### ISSUE TITLE
Improve UniqueID for devices

### ISSUE THREAD

**Issue by pvint** [vintlabs/fauxmoESP#126]
@pvint Is there any way to make the device id random or to set that myself?  I think I figured out why my 2nd successful discovery got the last 5 of my devices.  And that is because the ids of the 5 before those were the same ids as the first 5 devices that were discovered.  I know this sounds confusing, but it's a problem with the device ids being set programmatically.  I'd rather set the device id myself to something I know hasn't been already used.

_Originally posted by @jenniferlee1818 in https://github.com/vintlabs/fauxmoESP/issues/120#issuecomment-726451454_

**Comment by pvint** [comment]
Moved to a separate issue.

I've been thinking about better ways to handle the UniqueID, and I think the two things that are most important is for it to be (obviously), unique, but also repeatable.

My current idea is to use a hash of the device MAC along with the device's name. Something like this pseudo-code:
```
uniqueid = md5(mac + deviceName);
```

**Comment by jenniferlee1818** [comment]
One by one, I added and discovered all of my devices.
At fauxmoESP.cpp line 127, I changed id to 0.
 ```
snprintf_P(
        buffer, sizeof(buffer),
        FAUXMO_DEVICE_JSON_TEMPLATE,
        device.name, mac.substring(6).c_str(), id, 
        device.state ? "true": "false",
        device.value
    );
```
```
    fauxmo.addDevice("living room tv");   //0
    //fauxmo.addDevice("antenna tv");       //1
    //fauxmo.addDevice("cody");             //2
    //fauxmo.addDevice("volume up");        //3
    //fauxmo.addDevice("volume down");      //4
    //fauxmo.addDevice("channel up");       //5
    //fauxmo.addDevice("channel down");     //6
    //fauxmo.addDevice("mute");             //7
    //fauxmo.addDevice("c b s");            //8
    //fauxmo.addDevice("n b c");            //9
    //fauxmo.addDevice("fox");              //10
    //fauxmo.addDevice("a b c");            //11
    //fauxmo.addDevice("p b s");            //12
    //fauxmo.addDevice("p b s kids");       //13
    //fauxmo.addDevice("create");           //14
```
Upload sketch.  Do discovery.
Go back to fauxmoESP.cpp, change id to 1.  
```
    //fauxmo.addDevice("living room tv");   //0
    fauxmo.addDevice("antenna tv");       //1
    //fauxmo.addDevice("cody");             //2
    //fauxmo.addDevice("volume up");        //3
    //fauxmo.addDevice("volume down");      //4
    //fauxmo.addDevice("channel up");       //5
    //fauxmo.addDevice("channel down");     //6
    //fauxmo.addDevice("mute");             //7
    //fauxmo.addDevice("c b s");            //8
    //fauxmo.addDevice("n b c");            //9
    //fauxmo.addDevice("fox");              //10
    //fauxmo.addDevice("a b c");            //11
    //fauxmo.addDevice("p b s");            //12
    //fauxmo.addDevice("p b s kids");       //13
    //fauxmo.addDevice("create");           //14
```
Upload sketch.  Do discovery.
Go back to fauxmoESP.cpp, change id to 2.  And so on.  I did that for all 15 devices.

Last upload.  Don't do discovery.
 ```
    fauxmo.addDevice("living room tv");   //0
    fauxmo.addDevice("antenna tv");       //1
    fauxmo.addDevice("cody");             //2
    fauxmo.addDevice("volume up");        //3
    fauxmo.addDevice("volume down");      //4
    fauxmo.addDevice("channel up");       //5
    fauxmo.addDevice("channel down");     //6
    fauxmo.addDevice("mute");             //7
    fauxmo.addDevice("c b s");            //8
    fauxmo.addDevice("n b c");            //9
    fauxmo.addDevice("fox");              //10
    fauxmo.addDevice("a b c");            //11
    fauxmo.addDevice("p b s");            //12
    fauxmo.addDevice("p b s kids");       //13
    fauxmo.addDevice("create");           //14
```

I thought this would work, but now it doesn't matter what device I tell Alexa to turn on, the set state is always sent to living room tv. 

"Alexa, turn on fox."
```
[FAUXMO] TCP request
PUT /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights/1/state HTTP/1.1
Host: 10.0.0.18
Accept: */*
Content-Type: application/json
Content-Length: 11

{"on":true}
[FAUXMO] isGet: false
[FAUXMO] URL: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights/1/state
[FAUXMO] Body:
{"on":true}
[FAUXMO] Handling state request
[FAUXMO] Response:
HTTP/1.1 200 OK
Content-Type: text/xml
Content-Length: 81
Connection: close

[{"success":{"/lights/1/state/on":true}},{"success":{"/lights/1/state/bri":255}}]
[MAIN] Device #0 (living room tv) state: ON value: 255
[FAUXMO] Client #0 disconnected
[FAUXMO] Client #0 connected
[FAUXMO] TCP request
GET /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights/1 HTTP/1.1
Host: 10.0.0.18
Accept: */*
Content-Type: application/json


[FAUXMO] isGet: true
[FAUXMO] URL: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights/1
[FAUXMO] Handling list request
[FAUXMO] Response:
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 266
Connection: close

{"type":"Extended color light","name":"living room tv","uniqueid":"c1dc4b000000","modelid":"LCT015","state":{"on":true,"bri":255,"xy":[0,0],"reachable": true},"capabilities":{"certified":false,"streaming":{"renderer":true,"proxy":false}},"swversion":"5.105.0.21169"}
[FAUXMO] Client #0 disconnected


```

**Comment by jenniferlee1818** [comment]
fauxmoESP.cpp

`#include <MD5Builder.h>`

```
String byte2hex(byte Zahl){
  	String Hstring = String(Zahl, HEX);
  	if (Zahl < 16){Hstring = "0" + Hstring;}
  	return Hstring;
}

String makeMD5 (String text){
	byte bbuff[16];
  	String hash = "";
      	MD5Builder md5; 
      	md5.begin();
      	md5.add(text); 
      	md5.calculate(); 
      	md5.getBytes(bbuff);
      	for ( byte i = 0; i < 16; i++) hash += byte2hex(bbuff[i]);
      	return hash;   
}

String fauxmoESP::_deviceJson(unsigned char id) {

	if (id >= _devices.size()) return "{}";

	String mac = WiFi.macAddress();
        mac.replace(":", "");
        mac.toLowerCase();

	fauxmoesp_device_t device = _devices[id];
	
	mac.concat(device.name);
	
	String hash = makeMD5(mac).substring(0,16);  

    char buffer[strlen_P(FAUXMO_DEVICE_JSON_TEMPLATE) + 64];
    snprintf_P(
        buffer, sizeof(buffer),
        FAUXMO_DEVICE_JSON_TEMPLATE,
        device.name, hash.c_str(),
        device.state ? "true": "false",
        device.value
    );
	//free(hash);
	return String(buffer);

}


```

```
unsigned char fauxmoESP::addDevice(const char * device_name) {

	String mac = WiFi.macAddress();
        mac.replace(":", "");
        mac.toLowerCase();

    fauxmoesp_device_t device;
    unsigned int device_id = _devices.size();

    // init properties
    	device.name = strdup(device_name);
	device.state = false;
	device.value = 0;

    // Attach
    _devices.push_back(device);

    
        DEBUG_MSG_FAUXMO("[FAUXMO] Device '%s' added as #%d\n", device_name, device_id);
	mac.concat(device_name);
	String hash = makeMD5(mac).substring(0,16);

    return device_id;

}
```

[MD5.zip](https://github.com/vintlabs/fauxmoESP/files/5543167/MD5.zip)

**Comment by pvint** [comment]
Excellent! I spent a bunch of time on Friday thinking about this and looking into different methods to create a good hash to use for this and about any potential issues that might arise, and have been thinking about it over the weekend, and in the meantime it looks like you did it for me, thanks!

I'll test it out in a little bit... I presume it's working for you?

**Comment by pvint** [comment]
Also, @jenniferlee1818 - if you have a minute or two, would you mind doing this in a pull request on the dev branch? (I can do it if you want)

**Comment by jenniferlee1818** [comment]
Yes, it works and solves so many issues with discovery.  It's awesome because the unique id for each device is always the same.  I don't even know how to do a pull request, or what that means, but would love to learn.  Maybe I'll just try...

**Comment by pvint** [comment]
Yeah, give it a go... I requested to do it on the dev branch, but don't worry about that if it might get in your way.

My basic definition of a "Pull Request" is this: You have code changes that are useful to the project, and you can submit it (as a PR), and then I can choose to merge it in, and then it's "on record" that it was you who did that bit. Github actually makes it quite easy (but perhaps not always obvious)

**Comment by pvint** [comment]
Also, something I want to note:
I'm a bit worried that we might not want it to always be the same... I cannot come up with a situation off the top of my head where it would be bad to have a device with the same name running from the same ESP device having the same uniqueid, but there's a hint of paranoia there that I want to keep in mind.

**Comment by jenniferlee1818** [comment]
I can't figure out the pull request thingy.  Sorry!

**Comment by jenniferlee1818** [comment]
And I think the md5 in addDevice function isn't necessary.  I just wanted to see that there in the debug output.

**Comment by pvint** [comment]
That's ok - I can do it (I was just partially being lazy...). I might not do it until morning though (I'm in Canada, GMT-5).

**Comment by ddweber456** [comment]
@jenniferlee1818 great job, I'm looking forward to giving it a try.  Were you able to discover all 15 of your devices in a single pass?

**Comment by jenniferlee1818** [comment]
@ddweber456 no, I can only get 5 before watchdog reset.

**Comment by pvint** [comment]
@jenniferlee1818 - I have added your code and committed it to the master branch. Many thanks!

Also, referring to only being able to add 5 devices before it resets - I'm hoping to have a resolution for that soon.

**Comment by pvint** [comment]
Thinking about this more, I think I will reopen this. I think with the current method there's a couple potential pitfalls, the biggest being that if a device is renamed it will get a new uniqueid, and this may not always be desirable.

**Comment by pvint** [comment]
In commit 73ff88e I've added ability to manually set the device's uniqueid:
```C
void fauxmoESP::setDeviceUniqueId(unsigned char id, const char *uniqueid)
```

This can be run any time after a device is created, and this should take care of cases where you want to change a device name or even the host that a device runs on without changing the unique ID.

**Comment by jenniferlee1818** [comment]
@pvint More devices on one mcu would be great!  I have 3 nodemcu's piggybacking power to operate one little IR led.  But, it works!

**Comment by pvint** [comment]
> @pvint More devices on one mcu would be great! I have 3 nodemcu's piggybacking power to operate one little IR led. But, it works!

@jenniferlee1818  I'm curious about what you mean exactly, but I think it's a bit outside of the UniqueID topic. Really need a forum for general discussion stuff....  If you think it's related to FauxmoESP, feel free to open an issue here (but it doesn't sound like it is... you can send me an email about it if you wish, maybe I can help)
