### ISSUE TITLE
connection security, for example with locks

### ISSUE THREAD

**Issue by societyofrobots** [vintlabs/fauxmoESP#129]
Lets say I have a lock set up.

How would I prevent any user from using Alexa to discover the device and then unlocking it? Alexa has the ability to require a pin number for locks... how would I go about adding this ability with fauxmoESP?

**Comment by pvint** [comment]
I've been thinking about this for a few days now, and I cannot see any way we can do this. We are locked in (for the time being, anyway), to emulating Philips Hue bulbs, and with those there's no provision for anything like a PIN.
