### ISSUE TITLE
Discussion group / forum

### ISSUE THREAD

**Issue by pvint** [vintlabs/fauxmoESP#130]
I think it would be helpful to have a discussion group/forum for general discussion about FauxmoESP and related issues/projects. I've tried hosting a forum in the past, but keeping spammers at bay is just too time consuming.

I welcome any thoughts on how/where would be a good place to do this.

**Comment by WxAaRoNxW** [comment]
discord may be a great idea?

**Comment by pvint** [comment]
As it turns out, Github has discussions now!

https://github.com/vintlabs/fauxmoESP/discussions
