### ISSUE TITLE
How to send a message(String) from Alexa to ESP32?

### ISSUE THREAD

**Issue by DeathStrokeAlpha-VA** [vintlabs/fauxmoESP#154]
I have built a gateway that works on ESP32. The gateway controls the peripheral devices via ESP-NOW protocol. Is there a way by which Alexa can simply forward a string to ESP32, like, if the user says "Alexa, turn on light in kitchen", then, Alexa should forward "TURN ON LIGHT IN KITCHEN" to ESP32.

**Comment by sebkouba** [comment]
As I understand it sending a string like you asked is not possible.

If you look at the callback function you can see what is and is not possible at the moment:
```fauxmo.onSetState([](unsigned char device_id, const char * device_name, bool state, unsigned char value) ```

The ```bool state``` can only be true or false. The ```unsigned char``` can be 0-255. Fauxmo emulates a Philips Hue, according to the documentation, so you can only da what you can do to a light. In this case switch it on and off and send a value (for brightness I assume, originally).

I'm not sure what more is possible with more coding work but as I understand that's what we have right now.

**Comment by DeathStrokeAlpha-VA** [comment]
Thanks for the answer but I think this isn't possible with Alexa. I would have to create an Alexa Skill and point it to my MQTT server.

**Comment by pvint** [comment]
Yeah, not directly possible without creating an Alexa skill. Having said that, you can interpret what the command was by what the values are as @sebkouba said.
