### ISSUE TITLE
Error including library fauxmoESP.h

### ISSUE THREAD

**Issue by WirelessMind** [vintlabs/fauxmoESP#181]
Hello!
I'm importing the library in an already existing sketch, but I get numerous errors in importing different libraries concerning wifi:

`Compiling .pio\build\esp12e\lib354\WiFi\WiFi.cpp.o
In file included from C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\WiFi\src\ETH.h:24:0,
                 from C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\WiFi\src\ETH.cpp:21:
C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\WiFi\src\WiFi.h:29:25: fatal error: IPv6Address.h: No such file or directory

*********************************************************************
* Looking for IPv6Address.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:IPv6Address.h"
* Web  > https://platformio.org/lib/search?query=header:IPv6Address.h
*
*********************************************************************

 #include "IPv6Address.h"
                         ^
In file included from C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\WiFi\src\WiFi.cpp:24:0:
C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\WiFi\src\WiFi.h:29:25: fatal error: IPv6Address.h: No such file or directory

*********************************************************************
* Looking for IPv6Address.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:IPv6Address.h"
* Web  > https://platformio.org/lib/search?query=header:IPv6Address.h
*
*********************************************************************

 #include "IPv6Address.h"
                         ^
compilation terminated.
compilation terminated.
Compiling .pio\build\esp12e\lib354\WiFi\WiFiAP.cpp.o
*** [.pio\build\esp12e\lib354\WiFi\WiFi.cpp.o] Error 1
*** [.pio\build\esp12e\lib354\WiFi\ETH.cpp.o] Error 1
In file included from C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\WiFi\src\WiFiAP.cpp:25:0:
C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\WiFi\src\WiFi.h:29:25: fatal error: IPv6Address.h: No such file or directory

*********************************************************************
* Looking for IPv6Address.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:IPv6Address.h"
* Web  > https://platformio.org/lib/search?query=header:IPv6Address.h
*
*********************************************************************

 #include "IPv6Address.h"
                         ^
compilation terminated.
*** [.pio\build\esp12e\lib354\WiFi\WiFiAP.cpp.o] Error 1
In file included from C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/ESP8266WiFi.h:39:0,
                 from C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WebServer\src/ESP8266WebServer.h:29,
                 from src\main.cpp:16:
C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/WiFiClient.h:45:7: error: redefinition of 'class WiFiClient'
 class WiFiClient : public Client, public SList<WiFiClient> {
       ^
In file included from C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:36:0,
                 from src\main.cpp:14:
C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\WiFi\src/WiFiClient.h:39:7: error: previous definition of 'class WiFiClient'
 class WiFiClient : public ESPLwIPClient
       ^
In file included from C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/WiFiClientSecure.h:41:0,
                 from C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/WiFiServerSecure.h:20,
                 from C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,
                 from C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WebServer\src/ESP8266WebServer.h:29,
                 from src\main.cpp:16:
C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:38:5: error: 'BearSSL::WiFiClientSecure::~WiFiClientSecure()' marked override, but does not override
     ~WiFiClientSecure() override;
     ^
C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:43:9: error: 'int BearSSL::WiFiClientSecure::connect(const String&, uint16_t)' marked override, but does not override
     int connect(const String& host, uint16_t port) override;
         ^
C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:48:12: error: 'size_t BearSSL::WiFiClientSecure::write_P(const char*, size_t)' marked override, but does not override
     size_t write_P(PGM_P buf, size_t size) override;
            ^
C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:60:12: error: 'size_t BearSSL::WiFiClientSecure::peekBytes(uint8_t*, size_t)' marked override, but does not override
     size_t peekBytes(uint8_t *buffer, size_t length) override;
            ^
src\main.cpp: In function 'String httpGETRequest(String, String)':
src\main.cpp:467:26: warning: 'bool HTTPClient::begin(String)' is deprecated (declared at C:\users\microchip\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:174) [-Wdeprecated-declarations]
     http.begin(serverName);                                               //Specify request destination
                          ^
src\main.cpp:477:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
*** [.pio\build\esp12e\src\main.cpp.o] Error 1
================================================================================================== [FAILED] Took 3.65 seconds ==================================================================================================
The terminal process "C:\Users\Microchip\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload'" terminated with exit code: 1.
`

How should I do?

**Comment by pvint** [comment]
I don't use platformio, so I'm not sure how you do it, but it looks like doing a "make clean" might fix this.

**Comment by WirelessMind** [comment]
I done "clean", but it doesn't work :(

**Comment by pvint** [comment]
Unfortunately, that's correct. I hope we can find a way to do things like getting temperature, but that's a long time in the future likely.

**Comment by WirelessMind** [comment]
ok, thanks!
