### ISSUE TITLE
I ported fauxmoESP for Raspberry Pi Pico W

### ISSUE THREAD

**Issue by MrGreensWorkshop** [vintlabs/fauxmoESP#235]
Hi, I ported fauxmoESP for Raspberry Pi Pico W.
This is [the project](https://github.com/MrGreensWorkshop/arduinoPico_RasPiPicoW_AlexaEnabledSmartDevices/) with examples, if anyone interests.

**Comment by pvint** [comment]
Merged in 0b3aee19eac2797ac125aaab50b78a2a52e6ecf6 
Thank you!
