### ISSUE TITLE
'class fauxmoESP' has no member named 'onGetState'

### ISSUE THREAD

**Issue by jsalatiel** [vintlabs/fauxmoESP#236]
Hi,  to make alexa be able to get the current state for one device, it requires the onGetState callback, but apparently that callback was removed in version 3.0.
Any replacement for that ?

**Comment by jsalatiel** [comment]
https://github.com/vintlabs/fauxmoESP/issues/99

**Comment by MrGreensWorkshop** [comment]
Hi, please check [this commit](https://github.com/MrGreensWorkshop/ArduinoPico_RasPiPicoW_AlexaEnabledSmartDevices/commit/41754925ea4dc4241bab0a6e8053fe90ba9127dc). If @pvint agrees we can bring to this repo.

**Comment by jsalatiel** [comment]
Whats the signature for the   onGetState callback?
I tried:
```
  fauxmo.onGetState([](unsigned char device_id, const char * device_name) {
```
but it does not work:
```
/home/.../esp32/Arduino/libraries/fauxmoESP-3.4/src/fauxmoESP.h:100:14: note: candidate: void fauxmoESP::onGetState(TGetStateCallback)
         void onGetState(TGetStateCallback fn) { _getCallback = fn; }
/home/.../esp32/Arduino/libraries/fauxmoESP-3.4/src/fauxmoESP.h:100:14: note:   no known conversion for argument 1 from 'setup()::<lambda(unsigned char, const char*)>' to 'TGetStateCallback {aka std::function<void(unsigned char, const char*, bool&, unsigned char&)>}'

exit status 1
```

**Comment by MrGreensWorkshop** [comment]
Error explains itself. 

This is your definition...
fauxmo.onGetState([](unsigned char device_id, const char * device_name) {

This is what error says.
no known conversion to ->
{aka std::function<void(unsigned char, const char*, bool&, unsigned char&)>}

See the problem? If not please check how its used [here](https://github.com/MrGreensWorkshop/ArduinoPico_RasPiPicoW_AlexaEnabledSmartDevices/blob/main/examples/FauxmoPhilipsLight_Basic/FauxmoPhilipsLight_Basic.ino)

**Comment by jsalatiel** [comment]
Thanks. I am not a  programmer per se, so I still have problems to understand those errors. I could not find an example to that onGetState in the link you sent, but i suppose it uses the same args as the onSetState.

**Comment by MrGreensWorkshop** [comment]
please check the link again.

**Comment by jsalatiel** [comment]
I can see the onGetState call back being called and I am returning the correct value afaik.
1 for ON
0 for Off
But on alexa I still get "Device doesn't support requested value"

**Comment by MrGreensWorkshop** [comment]
when you ask "Alexa, is your_device_name is on?" You don't get correct answer. Did i understand you right?
what's your Amazon Alexa generation? 

Did you try with Alexa app? did you get correct on / off status there?

**Comment by jsalatiel** [comment]
3rd generation.

The alexa app shows me the message  "Device doesn't support requested value".
![image](https://user-images.githubusercontent.com/5522389/195991192-dfcaead2-58b8-407e-952e-ae9a94a70924.png)

"when you ask "Alexa, is your_device_name is on?" 
Alexa says ( translated from my language ) "Device is not compatible"

I can turn the devices on and off, but since alexa can not detect the current state it makes a two steps thing.

**Comment by jsalatiel** [comment]
In the onGetState callback I am printing some debug , so I see that alexa is running the getstate.
```
[ALEXA] 11:16:13 Getting current state for device #0 (buraco 1): ON
[ALEXA] 11:16:18 Getting current state for device #0 (buraco 1): ON
[ALEXA] 11:16:18 Getting current state for device #0 (buraco 1): ON
[ALEXA] 11:16:21 Getting current state for device #0 (buraco 1): ON
[ALEXA] 11:16:21 Getting current state for device #0 (buraco 1): ON
[ALEXA] 11:16:24 Getting current state for device #0 (buraco 1): ON
[ALEXA] 11:16:24 Getting current state for device #0 (buraco 1): ON
[ALEXA] 11:16:27 Getting current state for device #0 (buraco 1): ON
[ALEXA] 11:17:33 Getting current state for device #1 (buraco 2): OFF
```

**Comment by MrGreensWorkshop** [comment]
I see, what happens when you tap "buraco 1"? does it shows correct value screen after tapping.
as I told you at the beginning 
> It is working for me(gen1 and gen2)

I don't think I can help more than this. Sorry.

**Comment by jsalatiel** [comment]
"I see, what happens when you tap "buraco 1"? does it shows correct value screen after tapping"
Yes

"I don't think I can help more than this. Sorry."
Tks for all your help!

**Comment by jsalatiel** [comment]
@MrGreensWorkshop I have switched from this repo to FauxmoBelkinPlugfrom your repo and that works great!
Well, at least it works for esp32, unfortunatelly on esp8266-esp1 it does not work. ( the devices get not discovered ). Have you ever tested on esp8266 ?

**Comment by MrGreensWorkshop** [comment]
I didn't test with esp32. Actually I'm little surprised that it worked with esp32. Which AsyncTCP and Core version did you used for esp32?

It should work with esp8266 using Arduino core v2.3.0 and ESPAsyncTCP v1.1.2. Which version did you used when you testing esp8266?

**Comment by jsalatiel** [comment]
I have found the solution in another link for the esp8266. Sharing here:
I had to set  LwIP variant to "V2 higher bandwidth"
I suppose that the "V2 low memory"  sending 536 byte packets and "V2 higher bandwidth"  sending 1460 byte packets makes the difference here.

Now I have the same code working on both esp32 and esp8266-esp1
