### ISSUE TITLE
Strange behavior with command

### ISSUE THREAD

**Issue by sotana22** [vintlabs/fauxmoESP#249]
Hello, first I want to say many thanks to this great lib.

I have an issue with the voice command. I'm german, so my commands are normaly "an/aus"
In english it should be "on/off"
I use an ESP32 WROOM device.
Currently I use only one LED for testing at PIN 23.
So the Problem is:
- when I turn the LED on, I say "Alexa Device_Name on" (in german: "Alexa Device_Name an") in my case Device_Name is "BESTA_Schlafzimmer" -> LED turns on
- now I want to turn the light off and say "Alexa Device_Name off" (in german: "Alexa Device_Name aus") -> responce from Alexa, that she is not able to do it.
- then I try "Alexa Device_Name turn off" (in german "Alexa Device_Name  ausschalten") -> LED turns off
- on the other hand, if I also try "Alexa Device_Name turn on" (in german "Alexa Device_Name  einschalten") -> responce from Alexa, that there is no scene for this command.

For a Philips HUE lamp I can use the comands "on/off" and with fauxmoESP I have to use "on/turn off". Why?

**Comment by barneyz** [comment]
I use ESP_Alexa_Library, but it is the same concept behind. Sometimes I had have a similar issue. It helps then to rename the device to a "same" name, in my example Küchenschranklicht to Kuechenschranklicht or Couchlicht_3 to Couchlicht_drei in the Alexa App.

**Comment by sotana22** [comment]
Hello, thanks a lot for you comment.
Yes, I would understand it, if I have an Ö Ä Ü or a number, but which name should I use instead of BESTA_Schalfzimmer?

**Comment by barneyz** [comment]
It depends not to Umlaute, Couchlicht_3 to Couchlicht_drei was a real issue in the past....
Try to renaming a device in the alexa app is a 10 sec try, you can rename it back...

**Comment by sotana22** [comment]
Ok, I do not changed the name in the alexa app, but I changed the device name in the source code.
But at the end, it has the same effect, the name was changed.
I tried "Lego" and "Lego_Schlafzimmer". Both worked fine.
So it looks like, that there is a problem with BESTA?
