### ISSUE TITLE
Server is unresponsive and Incorrect Device Type

### ISSUE THREAD

**Issue by pvint** [vintlabs/fauxmoESP#98]
**[Original report](https://bitbucket.org/xoseperez/fauxmoesp/issue/98) by Bruce Miranda (Bitbucket: [Bruce Miranda](https://bitbucket.org/Bruce Miranda), ).**

----------------------------------------

I’ve been using the library successfully for a few weeks but then suddenly something seems to have changed. In the Alexa app I get a message saying “Server is unresponsive”. The Light Off command seems to work but then I cannot switch the Light back On because of the error. 

To attempt to solve the problem, I deleted the device and rediscovered it. Rediscovery works fine except now the device is no longer a Light - even though it’s shown as Hue Hub from Philips. The device is shown as “Other” and as a result I have no actions possible in the Alexa App.

**Comment by pvint** [comment]
As of now, I can confirm that it is working. I had experienced some of the "Server unresponsive" issues like mentioned above a few months back, but am not having any issue with it currently.  Note that controlling the devices using voice commands is really the core of this project, and whether or not it works in the app is secondary.

**Comment by JonS9999** [comment]
Hi pvint.

Could you please clue us in as to what you did to get it to start working again?  I'm still struggling with getting the ESP8266 device to be recognized by the Alexa App (it times out with "No new devices found.").

Thanks.

**Comment by pvint** [comment]
It appears that since a recent Amazon update we're having troubles getting discovery to work - see #120 

I'll be looking at it more tomorrow and I'll update.

Cheers
Paul
